name: Deploy Portfolio be

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'i-gabin-portfolio-be' #Must be unique in Heroku
          heroku_email: 's.ishimwegabin@gmail.com'
